//Dev: Rayyan
//Use Cases: UC5
package aval.domain.ai;

import java.util.UUID;

//@desc:   Represents the vector embedding of a StandardizedTransaction generated by the AI model.
//@grasp:  Information Expert
//@gof:    N/A
public class SemanticEmbedding {

    private final UUID transactionId;
    private final float[] vector;

    public SemanticEmbedding(UUID transactionId, float[] vector) {
        this.transactionId = transactionId;
        this.vector = vector;
    }

    public UUID getTransactionId() {
        return transactionId;
    }

    public float[] getVector() {
        return vector;
    }
}
